repos:
- repo: https://github.com/kajmaj87/pre-commit-rust
  rev: v1.0
  hooks:
  - id: fmt
  - id: clippy
  - id: cargo-check
  - id: cargo-test
- repo: local
  hooks:
  - id: cargo-outdated
    name: cargo outdated
    entry: bash -c 'cargo outdated -R --exit-code 1 || (echo "Dependencies need to be updated; run cargo update" && exit 1)'
    language: system
    types: [rust]
    pass_filenames: false

fail_fast: true
